### ISSUE TITLE
[Bug]: Errors with Interrupts module on load

### ISSUE THREAD

**Issue by aa-chrismcfadyen** [bkader/Skada-Damage-Meter#11]
### Are you using the latest version of the addon?

- [X] Yes
- [ ] No

### Addon Version

Version: 1.8.85 - Date: 2023-08-10 @ 12:39 UTC

### Did you try having only this addon enabled?

- [ ] Yes
- [X] No

### Current Behavior

There are 2 errors on login when loading the Interrupts module in 10.2.  These errors seem to prevent other modules after it from being loaded.  I tried clearing Skada's savedvariables and reinstalling from scratch to verify it still happens on a clean install, then restored my savedvariables.

### Expected Behavior

No errors upon login.

### Lua Error

First error:
```
Skada/Modules/Interrupts.lua:239: bad argument #2 to 'format' (string expected, got table)
[string "=[C]"]: ?
[string "@Skada/Modules/Interrupts.lua"]:239: in function <Skada/Modules/Interrupts.lua:233>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>
```

Second error:
```
Skada/Core/Options.lua:999: bad argument #3 to 'format' (string expected, got table)
[string "=[C]"]: ?
[string "@Skada/Core/Options.lua"]:999: in function `AddColumnOptions'
[string "@Skada/Core/Core.lua"]:1161: in function <Skada/Core/Core.lua:1154>
[string "@Skada/Core/Core.lua"]:1213: in function `AddMode'
[string "@Skada/Modules/Interrupts.lua"]:220: in function <Skada/Modules/Interrupts.lua:200>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
...
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:179: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:172: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:167: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:158: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:154>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:122: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>
```

### Reproduction Steps

1. Log into a character with Skada enabled

### Last Good Version

This was my first time installing the Revisited version

**Comment by bkader** [comment]
Hello @aa-chrismcfadyen  . Thanks for reporting this issue.
Please [try this version](https://bit.ly/SkadaMG) (_`Version: 1.8.86 - Date: 2023-11-09 @ 23:43`_) and see if the error still pops. Meanwhile, I will try to do dig a bit to see why this is happening (_get `3.4.x`, it's for both classic and retail_).

**Comment by aa-chrismcfadyen** [comment]
Still get the error, but no `missing entry <something>`.

This time I disabled all addons except Skada, BugSack and BugGrabber, and there's no error, including with 1.8.85.  I'm going to start winnowing down the addons that might be causing it, starting with ones that might have an Ace3 conflict

**Comment by aa-chrismcfadyen** [comment]
It is GladiusEx: https://www.curseforge.com/wow/addons/gladiusex that conflicts
It also uses AceAddon-3.0 and loads a `modules/interrupts.lua` (uses lower case though)

**Comment by bkader** [comment]
Thanks for taking time to check. Open that file `modules\interrupts.lua` at line **15** and change:
```lua
--- from: 
INTERRUPTS = GladiusEx.Data.Interrupts()
-- to:
local INTERRUPTS = GladiusEx.Data.Interrupts()
```
And if you can report this to the author it would be nice, tell them not to mess with **globals** as it affects other addons, instead they should use **locals** whenever possible.

**Comment by aa-chrismcfadyen** [comment]
Opened an issue about it over there, thanks!
