### ISSUE TITLE
[Bug]: 2 errors on login after March 22/24 update, making addon not function at all

### ISSUE THREAD

**Issue by aa-chrismcfadyen** [bkader/Skada-Damage-Meter#13]
### Are you using the latest version of the addon?

- [X] Yes
- [ ] No

### Addon Version

Version 1.8.86 - Date: 2024-03-22 @ 23:08 UTC

### Did you try having only this addon enabled?

- [ ] Yes
- [X] No

### Current Behavior

Error on login, bars are not displayed for any fight or mode and skin options have been reset.

Reverting to 1.8.85 has no issues.

### Expected Behavior

No errors, navigating through options to function.

### Lua Error

First error, on login:
```
12x Skada/Core/Display/Bar.lua:1067: bad argument #3 to 'SetFont' (Usage: self:SetFont(fontFile, height, flags))
[string "=[C]"]: in function `SetFont'
[string "@Skada/Core/Display/Bar.lua"]:1067: in function `ApplySettings'
[string "@Skada/Core/Core.lua"]:2271: in function `ApplySettings'
[string "@Skada/Core/Core.lua"]:1020: in function `CreateWindow'
[string "@Skada/Core/Core.lua"]:2343: in function `ReloadSettings'
[string "@Skada/Core/Core.lua"]:2463: in function <Skada/Core/Core.lua:2431>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:572: in function `UIParentLoadAddOn'
[string "@Rarity/Core/Collections.lua"]:63: in function `ScanToys'
[string "@Rarity/Core/Collections.lua"]:282: in function `ScanExistingItems'
[string "@Rarity/Core.lua"]:178: in function `DoEnable'
[string "@Rarity/Core.lua"]:150: in function <Rarity/Core.lua:149>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>
```

Error when switching between modes and fights:
```
8x Skada/Modules/Damage.lua:823: attempt to call method 'FormatNumber' (a nil value)
[string "@Skada/Modules/Damage.lua"]:823: in function `GetSetSummary'
[string "@Skada/Core/Core.lua"]:636: in function `UpdateDisplay'
[string "@Skada/Core/Core.lua"]:2056: in function `UpdateDisplay'
[string "@Skada/Core/Core.lua"]:895: in function `DisplayModes'
[string "@Skada/Core/Core.lua"]:953: in function `RightClick'
[string "@Skada/Core/Display/Bar.lua"]:76: in function <Skada/Core/Display/Bar.lua:65>
```

### Reproduction Steps

1. Log in
2. Right-click and click the different time segments/modes in Skada.

### Last Good Version

Last stable version I believe, which would be 1.8.85

**Comment by bkader** [comment]
Hi and thanks for reporting the issue @aa-chrismcfadyen .
Please try with only Skada enabled, no other addon. If it works then it's a conflict issue and only by enabling your add-ons one by one you can find out.

**Comment by aa-chrismcfadyen** [comment]
I was going to spend a couple hours today figuring out if it was other addons (I have 197 of them, so it would've been a while), but the last couple updates have fixed the error on login and everything seems to work well.  I lost my settings, but I had a backup SavedVariables file that I was able to use.  Thanks for saving me that time!
