### ISSUE TITLE
[Bug]: Skada: Window "Skada" was not loaded because its display module, "bar" was not found.

### ISSUE THREAD

**Issue by aa-chrismcfadyen** [bkader/Skada-Damage-Meter#16]
### Are you using the latest version of the addon?

- [X] Yes
- [ ] No

### Addon Version

Version: 1.8.87 - Date: 2024-03-23 @ 11:22 UTC

### Did you try having only this addon enabled?

- [X] Yes
- [ ] No

### Current Behavior
I logged in today and Skada wasn't showing.  When I opened up the config I got this:
![skadaerror](https://github.com/bkader/Skada-Damage-Meter/assets/123623/58275706-6299-42a6-a502-efc7a373f485)

Clicking the dropdown has about 6 empty rows.

I had changed the loaded modules on an alt last night, but that was specific to them and things were fine after reloading.

I tried disabling every addon except Skada, and the error still shows up.  "Bar.lua" exists in the Skada files, and re-installing the addon didn't change anything.

### Expected Behavior

No error in Skada

### Reproduction Steps

1. I really have no idea how this happened

**Comment by aa-chrismcfadyen** [comment]
Apologies for changing the issue a dozen times, I thought I was just going to report it and go to bed, but my inquisitive nature got the better of me.

**Comment by bkader** [comment]
No worries @aa-chrismcfadyen feel free to report any issues you encounter.
Try to go on **Module Options** and scroll all the way down to make sure you have the **Bar Display** module enabled.

**Comment by aa-chrismcfadyen** [comment]
Ah, I see: Checking off the modules doesn't enable them in that section, it disables them.  I had bar displayed checked off.
