### ISSUE TITLE
Github release

### ISSUE THREAD

**Issue by Pewtro** [bkader/Skada-Damage-Meter#2]
Would it be possible to release a github package for this much like there's done on https://github.com/bkader/Skada-WoTLK, so I can use that for managing the addon?

**Comment by Pewtro** [comment]
@bkader The releases done on the repo now don't contain packaged releases (such as those that can be seen here https://github.com/WeakAuras/WeakAuras2/releases )

**Comment by bkader** [comment]
@Pewtro I modified the releases but I am not sure if that's whay you meant/wanted.
