### ISSUE TITLE
Error in Skada Core after updating to 1.8.84-4

### ISSUE THREAD

**Issue by Stanzilla** [bkader/Skada-Damage-Meter#3]
### Description

Getting this error on login right on login

### Version

Classic Wrath

### Tested with only this addon

- [ ] Yes
- [X] No

### Lua Error

4x Skada/Core/Core.lua:108: attempt to index field 'mode' (a nil value)
[string "@Skada/Core/Core.lua"]:108: in function <Skada/Core/Core.lua:95>
[string "@Skada/Core/Core.lua"]:1192: in function `AddMode'
[string "@GTFO/GTFO_Skada.lua"]:225: in function <GTFO/GTFO_Skada.lua:209>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

### Reproduction Steps

1. Install addon
2. log in

**Comment by bkader** [comment]
Please make sure to delete  `GTFO_Skada.lua` from **GTFO** as it is [NOT COMPATIBLE](https://github.com/bkader/Skada-WoTLK/issues/99#issuecomment-1398876294) with this version of Skada unless the author updates it for. I will leave this issue open until you confirm the error is gone.
Also, if you were using the default Skada before, please make sure to follow installation steps, it's **IMPORTANT**.

**Comment by Stanzilla** [comment]
Okay so just deleting the file is not enough but changing GTFO to not load the module helped

**Comment by bkader** [comment]
Deleting the file helps, as long as you reload after you do it, which I assume you didn't (you reloaded by disabling GTFO Skada module).

**Comment by Stanzilla** [comment]
> Deleting the file helps, as long as you reload after you do it, which I assume you didn't (you reloaded by disabling GTFO Skada module).

Nah because GTFO still tries to load the file and errors because of that.

**Comment by Stanzilla** [comment]
@bkader You should consider renaming the addon then, there might be more addons that rely on the addon "Skada" to be the old one.

**Comment by sausje** [comment]
So this is still happening....
