### ISSUE TITLE
Ace3 version is outdated

### ISSUE THREAD

**Issue by Zivres** [bkader/Skada-Damage-Meter#6]
### Description

Lua error is happen. Replacing AceConfig in Libs directory with latest version (https://www.curseforge.com/wow/addons/ace3) helped for me.

### Version

Retail

### Tested with only this addon

- [ ] Yes
- [x] No

### Lua Error

Message: Interface/SharedXML/Settings/Blizzard_Category.lua:79: attempt to index local 'self' (a nil value)
Time: Sun Jul 23 17:28:03 2023
Count: 1
Stack: Interface/SharedXML/Settings/Blizzard_Category.lua:79: attempt to index local 'self' (a nil value)
[string "@Interface/SharedXML/Settings/Blizzard_Category.lua"]:79: in function <Interface/SharedXML/Settings/Blizzard_Category.lua:76>
[string "=[C]"]: ?
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:143: in function <...erface/SharedXML/Settings/Blizzard_SettingsPanel.lua:112>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsInbound.lua"]:51: in function <...face/SharedXML/Settings/Blizzard_SettingsInbound.lua:50>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Skada/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:2007: in function `?'
[string "@Interface/AddOns/Titan/TitanConfig.lua"]:2684: in main chunk

Locals: self = nil
name = "Панели"
description = nil
subcategory = <table> {
 GetID = <function> defined @Interface/SharedXML/Settings/Blizzard_Category.lua:13
 SetCategorySet = <function> defined @Interface/SharedXML/Settings/Blizzard_Category.lua:53
 order = 11
 HasSubcategories = <function> defined @Interface/SharedXML/Settings/Blizzard_Category.lua:72
 CreateSubcategory = <function> defined @Interface/SharedXML/Settings/Blizzard_Category.lua:76
 SetParentCategory = <function> defined @Interface/SharedXML/Settings/Blizzard_Category.lua:45
 HasParentCategory = <function> defined @Interface/SharedXML/Settings/Blizzard_Category.lua:49
 SetOrder = <function> defined @Interface/SharedXML/Settings/Blizzard_Category.lua:29
 ID = 11
 Init = <function> defined @Interface/SharedXML/Settings/Blizzard_Category.lua:6
 GetParentCategory = <function> defined @Interface/SharedXML/Settings/Blizzard_Category.lua:41
 GetName = <function> defined @Interface/SharedXML/Settings/Blizzard_Category.lua:17
 name = "Панели"
 SetName = <function> defined @Interface/SharedXML/Settings/Blizzard_Category.lua:21
 subcategories = <table> {
 }
 GetOrder = <function> defined @Interface/SharedXML/Settings/Blizzard_Category.lua:25
 GetQualifiedName = <function> defined @Interface/SharedXML/Settings/Blizzard_Category.lua:33
 GetSubcategories = <function> defined @Interface/SharedXML/Settings/Blizzard_Category.lua:68
 GetCategorySet = <function> defined @Interface/SharedXML/Settings/Blizzard_Category.lua:57
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = <table> {
 GetID = <function> defined @Interface/SharedXML/Settings/Blizzard_Category.lua:13
 SetCategorySet = <function> defined @Interface/SharedXML/Settings/Blizzard_Category.lua:53
 order = 11
 HasSubcategories = <function> defined @Interface/SharedXML/Settings/Blizzard_Category.lua:72
 CreateSubcategory = <function> defined @Interface/SharedXML/Settings/Blizzard_Category.lua:76
 SetParentCategory = <function> defined @Interface/SharedXML/Settings/Blizzard_Category.lua:45
 HasParentCategory = <function> defined @Interface/SharedXML/Settings/Blizzard_Category.lua:49
 SetOrder = <function> defined @Interface/SharedXML/Settings/Blizzard_Category.lua:29
 ID = 11
 Init = <function> defined @Interface/SharedXML/Settings/Blizzard_Category.lua:6
 GetParentCategory = <function> defined @Interface/SharedXML/Settings/Blizzard_Category.lua:41
 GetName = <function> defined @Interface/SharedXML/Settings/Blizzard_Category.lua:17
 name = "Панели"
 SetName = <function> defined @Interface/SharedXML/Settings/Blizzard_Category.lua:21
 subcategories = <table> {
 }
 GetOrder = <function> defined @Interface/SharedXML/Settings/Blizzard_Category.lua:25
 GetQualifiedName = <function> defined @Interface/SharedXML/Settings/Blizzard_Category.lua:33
 GetSubcategories = <function> defined @Interface/SharedXML/Settings/Blizzard_Category.lua:68
 GetCategorySet = <function> defined @Interface/SharedXML/Settings/Blizzard_Category.lua:57
}
(*temporary) = nil
(*temporary) = "attempt to i

### Reproduction Steps

1. Install addon
2. Start a game

**Comment by bkader** [comment]
Hello @Zivres .. Thanks for reporting this, I will check it asap.
