### ISSUE TITLE
[Bug]: Error on login

### ISSUE THREAD

**Issue by Stanzilla** [bkader/Skada-Damage-Meter#9]
### Are you using the latest version of the addon?

- [X] Yes
- [ ] No

### Addon Version

Skada: Version: 1.8.85 - Date: 2023-08-10 @ 12:39 UTC

### Did you try having only this addon enabled?

- [ ] Yes
- [X] No

### Current Behavior

Error

### Expected Behavior

No Error

### Lua Error

32x Skada/Core/Display/Bar.lua:154: attempt to compare nil with number
[string "@Skada/Core/Display/Bar.lua"]:154: in function `Create'
[string "@Skada/Core/Core.lua"]:974: in function `CreateWindow'
[string "@Skada/Core/Core.lua"]:2228: in function `ReloadSettings'
[string "@Skada/Core/Core.lua"]:2347: in function <Skada/Core/Core.lua:2316>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:544: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:753: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:179: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:172: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:167: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:158: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:154>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:122: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:363
 GetBarGroup = <function> defined @Skada/Libs/SpecializedLibBars-1.0/SpecializedLibBars-1.0.lua:483
 WindowStretchStart = <function> defined @Skada/Core/Display/Bar.lua:409
 EnableModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 baseName = "Skada"
 IterateEmbeds = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:438
 BarClick = <function> defined @Skada/Core/Display/Bar.lua:556
 BarLeave = <function> defined @Skada/Core/Display/Bar.lua:262
 WindowResized = <function> defined @Skada/Core/Display/Bar.lua:359
 WindowStretching = <function> defined @Skada/Core/Display/Bar.lua:402
 IsShown = <function> defined @Skada/Core/Display/Bar.lua:229
 Show = <function> defined @Skada/Core/Display/Bar.lua:216
 defaultModuleState = true
 WindowLocked = <function> defined @Skada/Core/Display/Bar.lua:396
 SetTitle = <function> defined @Skada/Core/Display/Bar.lua:235
 DisableModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:346
 callbacks = <table> {
 }
 Update = <function> defined @Skada/Core/Display/Bar.lua:708
 db = <table> {
 }
 SetEnabledState = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:420
 OnModuleCreated = <function> defined @Skada/Core/Functions.lua:35
 ScrollStart = <function> defined @Skada/Core/Display/Bar.lua:1001
 IterateModules = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:433
 GetBars = <function> defined @Skada/Libs/SpecializedLibBars-1.0/SpecializedLibBars-1.0.lua:528
 Wipe = <function> defined @Skada/Core/Display/Bar.lua:203
 localeName = "Bar Display"
 OnInitialize = <function> defined @Skada/Core/Display/Bar.lua:2537
 NewModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:231
 GetModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:206
 EndScroll = <function> defined @Skada/Core/Display/Bar.lua:1008
 defaultModuleLibraries = <table> {
 }
 Hide = <function> defined @Skada/Core/Display/Bar.lua:223
 Destroy = <function> defined @Skada/Core/Display/Bar.lua:196
 BarEnter = <function> defined @Skada/Core/Display/Bar.lua:253
 GetName = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:275
 RegisterCallback = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 GetBarGroups = <function> defined @Skada/Libs/SpecializedLibBars-1.0/SpecializedLibBars-1.0.lua:488
 WindowMoveStop = <function> defined @Skada/Core/Display/Bar.lua:312
 orderedModules = <table> {
 }
 Disable = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:310
 OnAnchorFrame = <function> defined @Skada/Core/Display/Bar.lua:446
 GetBar = <function> defined @Skada/Libs/SpecializedLibBars-1.0/SpecializedLibBars-1.0.lua:523
 description = "Bar display is the normal bar window used by most damage meters. It can be extensively styled."
 IsModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:213
 Enable = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:290
 SetDefaultModuleState = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:383
 ReleaseBar = <function> defined @Skada/Libs/SpecializedLibBars-1.0/SpecializedLibBars-1.0.lua:536
 OnEnable = <function> defined @Skada/Core/Display/Bar.lua:2520
 ApplySettings = <function> defined @Skada/Core/Display/Bar.lua:1027
 AddDisplayOptions = <function> defined @Skada/

### Reproduction Steps

Log in

**Comment by bkader** [comment]
Hello @Stanzilla and thanks for reporting this issue.
I am very aware of it and I have applied a fix for it that will be pushed to the next update. This error likely happens when you import old/external profiles.

If you cannot wait for the update, [please download this file](https://cdn.discordapp.com/attachments/779090711890886706/1139876917537931264/Bar.lua) and put it inside `Skada\Core\Display` folder. Make sure it asks you to replace the file, otherwise you'd be in the wrong folder.

Leave this issue open and I will close it when the time comes.
Thanks!
